luminaraio/environment-one-piece-staging

- env/Chart.yaml
- env/requirements.yaml
chore: Promote test-lib to version 1.0.0
> chore: test-lib to 1.0.0

- env/requirements.yaml
> Delete application test-lib from this environment

- env/requirements.yaml
chore: Promote vertx-web-quickstart-test2 to version 0.0.1
> chore: vertx-web-quickstart-test2 to 0.0.1

- env/requirements.yaml
chore: Promote test-vertx-web to version 0.0.1
> chore: test-vertx-web to 0.0.1

- env/requirements.yaml
> Delete application test-vertx-web from this environment

- env/requirements.yaml
chore: Promote test-vertx-grpc to version 0.0.2
> chore: test-vertx-grpc to 0.0.2

- env/requirements.yaml
chore: Promote test-vertx-web to version 0.0.3
> chore: test-vertx-web to 0.0.3

- env/requirements.yaml
The command `jx delete application` was run by afrey and it generated this Pull Request
> Delete application vertx-web-quickstart-test2 from this environment

- env/requirements.yaml
chore: Promote vert-web-buildpack-test to version 0.0.1
> chore: vert-web-buildpack-test to 0.0.1

- env/requirements.yaml
> Delete application test-vertx-grpc from this environment

- env/requirements.yaml
chore: Promote vertx-grpc-sample to version 0.0.2
> chore: vertx-grpc-sample to 0.0.2

- env/requirements.yaml
chore: Promote vertx-grpc-sample to version 0.0.3
> chore: vertx-grpc-sample to 0.0.3

- env/requirements.yaml
> Delete application vertx-grpc-sample from this environment

- env/requirements.yaml
chore: Promote test-vertx-grpc to version 0.0.1
> chore: test-vertx-grpc to 0.0.1

- env/requirements.yaml
chore: Promote test-vertx-web to version 0.0.4
> chore: test-vertx-web to 0.0.4

- env/requirements.yaml
chore: Promote test-vertx-web to version 0.0.5
> chore: test-vertx-web to 0.0.5

- env/requirements.yaml
chore: Promote test-vertx-web to version 0.0.6
> chore: test-vertx-web to 0.0.6

- env/requirements.yaml
chore: Promote test-vertx-web to version 0.0.7
> chore: test-vertx-web to 0.0.7

- env/requirements.yaml
chore: Promote test-vertx-web to version 0.0.8
> chore: test-vertx-web to 0.0.8

- .idea/$PRODUCT_WORKSPACE_FILE$
- .idea/modules.xml
- .idea/staging.iml
- .idea/vcs.xml
- .idea/workspace.xml
- env/requirements.yaml
> Delete application vert-grpc-buildpack-test from this environment

- .idea/workspace.xml
- env/requirements.yaml
> Delete application vert-web-buildpack-test from this environment

- env/requirements.yaml
chore: Promote simple-service to version 0.0.1
> chore: simple-service to 0.0.1

- env/requirements.yaml
chore: Promote simple-gateway to version 0.0.2
> chore: simple-gateway to 0.0.2

- env/requirements.yaml
chore: Promote simple-gateway to version 0.0.3
> chore: simple-gateway to 0.0.3

- env/requirements.yaml
chore: Promote simple-greeter-one to version 0.0.1
> chore: simple-greeter-one to 0.0.1

- env/requirements.yaml
chore: Promote simple-greeter-one to version 0.0.2
> chore: simple-greeter-one to 0.0.2

- env/requirements.yaml
chore: Promote simple-greeter-two to version 0.0.1
> chore: simple-greeter-two to 0.0.1

- env/requirements.yaml
chore: Promote simple-greeter-gateway to version 0.0.2
> chore: simple-greeter-gateway to 0.0.2

- env/requirements.yaml
chore: Promote simple-greeter-two to version 0.0.2
> chore: simple-greeter-two to 0.0.2

- env/requirements.yaml
chore: Promote simple-greeter-two to version 0.0.3
> chore: simple-greeter-two to 0.0.3

- env/requirements.yaml
chore: Promote web-service-test to version 0.0.1
> chore: web-service-test to 0.0.1

- env/requirements.yaml
The command `jx delete application` was run by afrey and it generated this Pull Request
> Delete application web-service-test from this environment
